version: "3.9"
services:
  postgres:
    image: postgres:10.5
    container_name: db
    networks:
      - default
    restart: always
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - 5438:5432
    volumes:
      - ./app/sql/init_schema.sql:/docker-entrypoint-initdb.d/init_schema.sql
  
  app:
    build: .
    container_name: app
    networks:
      - default
    depends_on:
      - postgres
    restart: "on-failure"